### ISSUE TITLE
Fix for backwards incompatible change to Rcpp::string handling of encoding

### ISSUE THREAD

**Issue by asieira** [asieira/SnakeCharmR#24]
The Rcpp team, in their infinite wisdom, decided to make a [breaking change to public methods of the string class](https://github.com/RcppCore/Rcpp/commit/0bf8e97e46ff85d02d7f158c6b476369f7912cc1) and publish that as a minor version change to 0.12.7.

Now I need to refactor the code to ensure it continues to work properly.

A big thank you to @davidski for bringing this to my attention.

**Comment by eddelbuettel** [comment]
Please chill.  We reverse-depends check on EVERY released CRAN package.

You got unlucky because your package was not yet on CRAN.  You may also be unlucky because you create strings from further deep down than other people.   We are not aware of breakage of a single package -- else CRAN maintainers would not have let us onto CRAN.  Now as for [what you have there](https://github.com/asieira/SnakeCharmR/blob/master/src/python.cpp#L30-L36) I am not even sure you are better off using the `CE` encoding.  

/cc @kevinushey @thirdwing @jjallaire  Any views?  Glance at the link above for a six line segment

**Comment by asieira** [comment]
Glad to hear you reverse-depends check on every released CRAN package. That certainly is one way to reduce the impact of a backwards-incompatible change.

However, Rcpp is not exclusively used on CRAN packages, as my not yet published package exemplifies. I can only imagine many people must use a useful package such as Rcpp on proprietary code as well as on packages available only on GitHub for various reasons. So checking CRAN packages is good, but IMHO not nearly enough.

IMHO the correct thing to have done would have been to do the following in order:
- Try as hard as possible to keep the old encoding methods working with strings instead of CE encoding constants, marking them as deprecated; and adding new ones that work with the CE encoding. To be fair, I haven't reviewed the change in detail and don't know enough about Rcpp internals to judge how hard this was attempted, if at all, or even if it is possible.
- As per semantic versioning, if you have exhausted the above and will push a backwards-incompatible change, then please update the major version. Don't treat this as a patch level update only as was done here (0.12.6 -> 0.12.7).

Having said all that, I completely understand Rcpp is open source software (and very good software at that). I am in no position to demand anything from you. Any decisions made by the Rcpp maintainers are final, and anyone that chooses to use Rcpp has to accept them, myself included. So I didn't make any fuss about it, other than working around the change on my own code and making a funny comment about it in my issue.

I appreciate all the hard work you put into Rcpp, and find it extremely useful. Thank you very much for that. But I also reserve the right to respectfully disagree with your decision in this situation. Fair?

**Comment by eddelbuettel** [comment]
Let's just agree to disagree here, and feel free to peruse our (public) discussion on the issue(s) and PR(s) related to this.   We did not, and do not, consider this a breaking change and have not heard of a _single_ instance of required code change -- before your change here.   So it looks like a mountain versus mole hill issue to me. Of course it's important to you; it didn't seem to have affected anybody else.  We are rather careful about change management with Rcpp as we are well aware of its wide usage.

**Comment by asieira** [comment]
You seem to be conflating two completely independent claims here:

a) Whether the changes you introduced are breaking / backwards-incompatible or not;
b) Whether any relevant amount of code exists that uses the affected part of the Rcpp API and as such will be actually broken.

You seem to be arguing that B is false and that this somehow implies that A is also false. I disagree.

First of all, neither you nor I have access to all code that uses Rcpp, as I explained on my previous comment. So B is unknowable. But even if we did know that no one in the universe ever used `String::get_encoding` and `String::set_encoding` that would still not say anything about whether A is true or not, only what the impact of A being true is.

All it takes to prove that A is true is to show that there was a change in Rcpp's public API such there it is possible to write valid code under 0.12.6 that is no longer valid under 0.12.7. 

And that is as easy as writing the expression `String("foo").get_encoding() == "UTF-8"`. This is perfectly valid under 0.12.6 and only uses the Rcpp's public API at the time. But in 0.12.7 you did a backwards-incompatible change to the String class public methods. You changed `get_encoding` to have a return type of `cetype_t`, which is not a subclass of the previous return type `std::string`. So, this previously functioning C++ expression will now fail to type check and generate a compiler error.

So yes, I think it's pretty clear that the change from 0.12.6 to 0.12.7 made backwards incompatible changes to Rcpp's public API.

**Comment by kevinushey** [comment]
Yes, this was a backwards-incompatible change. As @eddelbuettel said, we assumed we were in the clear as it did not affect any packages on CRAN, and the `String` class is overall not too widely used by client packages.

We're sorry for generating a bit more work for you. We believe the change is overall for the better as we now avoid exposing a 'string'ly-typed API (whoops, you typed `"utf-8"` instead of `"UTF-8"`), we force users to be upfront about their declared encodings (rather than ignoring it / getting it wrong when constructing a `String` object from a C string).

Yes, it likely would have been better if we had preserved the old API / made this change according to semantic versioning, but ... we didn't. Sorry.

Let's please halt this discussion as we're now wasting much more time than the few lines of code you made to accommodate this change did.

**Comment by asieira** [comment]
I agree, @kevinushey. Thank you.

In closing, I'd like to point out that this very scenario has been conveniently covered in the Semantic Versioning FAQ, so I'll post a link here and let you decide what (if anything) to do about it: http://semver.org/#what-do-i-do-if-i-accidentally-release-a-backwards-incompatible-change-as-a-minor-version

Thanks again for writing Rcpp and making it open source. ❤️

**Comment by eddelbuettel** [comment]
I find Semantic Versioning, and its very exuberant fans, exactly as inspiring as the CoC diehards. In other words not very.

You still imply that we _knowingly made a breaking change_.  We didn't it.  

And we essentially almost never do, or at least try our hardest not to.  (Errors happen, as the ill-fated PR with `NORET` which needed R >= 3.2.\* -- but because they are so visible we work hard to avoid them.)  

I am done with this.

**Comment by eddelbuettel** [comment]
One more:  I do have a lot of respect for Tom and love his TOML spec.  I just find SemVer too heavy handed and like the essentially-equivalent-but-lighter GNU versioning.  Now, _your_ link to his SemVer FAQ is still completely misplaced as it wasn't even an inadvertent change.  This was done on purpose so that we can now create strings with better encoding at the source.  Re-read Kevin's comment.

**Comment by asieira** [comment]
I did not mean to imply that you did anything _on purpose_, @eddelbuettel, and tried as hard as I could to keep the discussion focused on the facts and not on the people involved and their motivations. I apologize if I failed to communicate clearly and gave anyone a different impression.

Having said that, my opinion and my understanding of @kevinushey's opinion is that this was indeed a breaking change, however justified and useful.

Of course, it is up to you to decide whether to follow semantic versioning (or any particular scheme) or not. I would just like to suggest that if you don't, please add what logic your versioning does follow to the package documentation, so as to set Rcpp's users' expectations correctly.

**Comment by eddelbuettel** [comment]
Sorry, but _you_ started this via 

> The Rcpp team, in their infinite wisdom, ...

You could have filed an issue ticket at our end. We don't hide.  Instead you vented here. I checked your issue tickets before filing a new ticket (ie #29 which you ignored so far; I also accidentally filed twice in #28) and took exception, and still do.

You can always read our ChangeLog and NEWS.Rd. They summarize changes, as well as releases.

**Comment by asieira** [comment]
I addressed my original joke and why I decided to simply work around this issue in SnakeCharmR in the last two paragraphs of my first response to you, and have nothing to add besides what I've already said on this subject.

Since you brought up the Rcpp ChangeLog and NEWS.Rd files, I did read them and was unable to find any reference whatsoever to the fact that this release featured a breaking change of the String class API, only that the default encoding changed to UTF-8:

https://github.com/RcppCore/Rcpp/blob/master/ChangeLog#L78-L82

```
2016-08-02 Qiang Kou <qkou@umail.iu.edu>

        * inst/include/Rcpp/String.h: CE_UTF8 as default encoding
        * inst/unitTests/cpp/String.cpp: Update unit test
        * inst/unitTests/runit.String.R: Idem
```

https://github.com/RcppCore/Rcpp/blob/master/inst/NEWS.Rd#L32-L33

```
String constructors now set default UTF-8 encoding (Qiang Kou in #529 fixing #263).
```

I would like to respectfully suggest that you _do_ clearly document on these files that a backwards-incompatible change of the encoding handling of the String class was introduced.
